name: Test Frontend
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mrnogues/react-test -f frontend/Dockerfile.dev frontend
      - run: docker run -e CI=true mrnogues/react-test npm test
          
    